// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace InfoPanelsScssNamespace {
  export interface IInfoPanelsScss {
    infoPanels: string;
    moves: string;
  }
}

declare const InfoPanelsScssModule: InfoPanelsScssNamespace.IInfoPanelsScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InfoPanelsScssNamespace.IInfoPanelsScss;
};

export = InfoPanelsScssModule;
