[build]
  command = "pnpm turbo run build --filter=@tiles-town/web"
  publish = "apps/web/dist"

[[redirects]]
  from = "/api/*"
  to = "https://tiles-town-backend.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
