// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace TileScssNamespace {
  export interface ITileScss {
    active: string;
    back: string;
    coords: string;
    disabled: string;
    flipped: string;
    front: string;
    inactive: string;
    tile: string;
    tileInside: string;
  }
}

declare const TileScssModule: TileScssNamespace.ITileScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TileScssNamespace.ITileScss;
};

export = TileScssModule;
