// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace HighScoresScssNamespace {
  export interface IHighScoresScss {
    highScores: string;
  }
}

declare const HighScoresScssModule: HighScoresScssNamespace.IHighScoresScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HighScoresScssNamespace.IHighScoresScss;
};

export = HighScoresScssModule;
