// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace GameScssNamespace {
  export interface IGameScss {
    boldTip: string;
    example: string;
    exampleBox: string;
  }
}

declare const GameScssModule: GameScssNamespace.IGameScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GameScssNamespace.IGameScss;
};

export = GameScssModule;
