// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace NewGamePanelScssNamespace {
  export interface INewGamePanelScss {
    newGamePanel: string;
  }
}

declare const NewGamePanelScssModule: NewGamePanelScssNamespace.INewGamePanelScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NewGamePanelScssNamespace.INewGamePanelScss;
};

export = NewGamePanelScssModule;
