// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace BoardScssNamespace {
  export interface IBoardScss {
    boardRow: string;
  }
}

declare const BoardScssModule: BoardScssNamespace.IBoardScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: BoardScssNamespace.IBoardScss;
};

export = BoardScssModule;
